# Generated by Django 4.2.28 on 2026-02-21 13:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.UUIDField(db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")], max_length=10
                    ),
                ),
                ("content", models.TextField()),
                ("temperature_used", models.FloatField(blank=True, null=True)),
                ("max_tokens_used", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("d_model", models.IntegerField(default=64)),
                ("n_heads", models.IntegerField(default=4)),
                ("n_layers", models.IntegerField(default=2)),
                ("d_ff", models.IntegerField(default=256)),
                ("seq_len", models.IntegerField(default=64)),
                ("vocab_size", models.IntegerField(default=0)),
                ("batch_size", models.IntegerField(default=16)),
                ("learning_rate", models.FloatField(default=0.001)),
                ("max_epochs", models.IntegerField(default=100)),
                ("grad_clip", models.FloatField(default=1.0)),
                ("beta1", models.FloatField(default=0.9)),
                ("beta2", models.FloatField(default=0.999)),
                ("epsilon", models.FloatField(default=1e-08)),
                ("max_gen_len", models.IntegerField(default=200)),
                ("temperature", models.FloatField(default=0.8)),
                ("seed", models.IntegerField(default=42)),
                ("log_every", models.IntegerField(default=10)),
                ("is_preset", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainedModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("weights_path", models.CharField(max_length=500)),
                ("total_parameters", models.IntegerField(default=0)),
                ("final_loss", models.FloatField(blank=True, null=True)),
                ("epochs_trained", models.IntegerField(default=0)),
                ("training_duration_seconds", models.FloatField(blank=True, null=True)),
                ("vocab_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trained_models",
                        to="api.modelconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploads/")),
                ("file_type", models.CharField(max_length=20)),
                ("file_size", models.IntegerField()),
                ("extracted_text", models.TextField(blank=True, default="")),
                ("char_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("stopped", "Stopped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_epoch", models.IntegerField(default=0)),
                ("total_epochs", models.IntegerField(default=0)),
                ("loss_history", models.JSONField(default=list)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_runs",
                        to="api.modelconfig",
                    ),
                ),
                (
                    "trained_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.trainedmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
