# Generated by Django 5.2.11 on 2026-02-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_trainingdata_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconfig",
            name="tokenizer_type",
            field=models.CharField(
                choices=[
                    ("character", "Caractère par caractère"),
                    ("gpt4", "GPT-4 (tiktoken)"),
                    ("claude", "Claude-like (tiktoken)"),
                ],
                default="character",
                max_length=20,
            ),
        ),
    ]
