# Generated by Django 5.2.11 on 2026-02-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_modelconfig_tokenizer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconfig",
            name="sampling_strategy",
            field=models.CharField(
                choices=[
                    ("greedy", "Glouton"),
                    ("temperature", "Température"),
                    ("top_k", "Top-K"),
                    ("top_p", "Top-P (nucleus)"),
                ],
                default="temperature",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="modelconfig",
            name="top_k",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="modelconfig",
            name="top_p",
            field=models.FloatField(default=0.9),
        ),
    ]
