# Generated by Django 4.2.28 on 2026-02-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_modelconfig_sampling_strategy_modelconfig_top_k_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconfig",
            name="weight_decay",
            field=models.FloatField(default=0.0),
        ),
    ]
