# Generated by Django 4.2.28 on 2026-02-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_add_weight_decay"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconfig",
            name="lr_schedule",
            field=models.CharField(
                choices=[
                    ("constant", "Constant"),
                    ("cosine", "Cosine Annealing"),
                    ("cosine_restarts", "Cosine avec redémarrages"),
                ],
                default="constant",
                max_length=20,
            ),
        ),
    ]
