# Generated by Django 4.2.28 on 2026-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_add_lr_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconfig",
            name="training_data",
            field=models.ManyToManyField(blank=True, related_name="configs", to="api.trainingdata"),
        ),
    ]
